server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafy?autoReconnect=true
    username: ssafy
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  data:
    redis:
#      lettuce:
#        pool:
#          max-active: 5
#          max-idle: 5
#          min-idle: 2
      host: ${redis.host}
      port: ${redis.port}


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace