jwt:
  secret: ${JWT_SECRET_KEY}
  # 60 * 30 * 10000ms (30min)
  access-expired: ${JWT_ACCESS_EXPIRED}
  # 7 * 24 * 60 * 60 * 1000ms (7day)
  refresh-expired: ${JWT_REFRESH_EXPIRED}

cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS}
